# Generated by Django 2.2.2 on 2019-08-01 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baskets', '0002_auto_20190801_1628'),
        ('users', '0003_customerprofile_smsmessage_washerprofile_workerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='customer_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.CustomerProfile'),
        ),
    ]
