# Generated by Django 2.2.2 on 2019-08-01 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_customerprofile_smsmessage_washerprofile_workerprofile'),
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='customer_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='users.CustomerProfile'),
        ),
    ]
